import axios from 'axios';
const api = axios.create({baseURL: process.env.REACT_APP_API_URL || 'http://localhost:8000', timeout: 15000});
api.interceptors.request.use(config => { const token = sessionStorage.getItem('datashield_token'); if (token) config.headers.Authorization = `Bearer ${token}`; return config; });
api.interceptors.response.use(r => r, error => { if (error.response?.status === 401 && !error.config?.url?.includes('/auth/login')) { sessionStorage.removeItem('datashield_token'); window.location.assign('/login'); } return Promise.reject(error); });
export const login = (username,password) => api.post('/api/v1/auth/login',{username,password});
export const me = () => api.get('/api/v1/auth/me');
export const alerts = params => api.get('/api/v1/alerts',{params});
export const alert = id => api.get(`/api/v1/alerts/${id}`);
export const decide = (id,action,notes) => api.post(`/api/v1/alerts/${id}/decisions`,{action,notes});
export const summary = days => api.get('/api/v1/reports/summary',{params: days?{days}:{}});
export const exportReport = days => api.get('/api/v1/reports/export',{params:{days},responseType:'blob'});
export const activity = () => api.get('/api/v1/users/activity');
export const userTimeline = id => api.get(`/api/v1/users/${id}/timeline`);
export const status = () => api.get('/api/v1/system/status');
export const policy = () => api.get('/api/v1/policies');
export const savePolicy = data => api.put('/api/v1/policies',data);
export const audit = () => api.get('/api/v1/audit');
export default api;
